#!/bin/bash

## Looking for config-files
if [ ! -f ~/.config/poweriso.conf ]; then
    touch ~/.config/poweriso.conf
    echo "LNG=EN" >> ~/.config/poweriso.conf
    echo "DEFAULTDIR=/home/$USER/" >> ~/.config/poweriso.conf
    echo "ASKFIRST=default" >> ~/.config/poweriso.conf
fi

. ~/.config/poweriso.conf
. /usr/share/poweriso/translations/translations

while [ "$ASKFIRST" != "" ]
do
ASKFIRST=$(zenity --list --radiolist --width=350 --height=250 --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png \
     --column="" --column="$CHOOSE_ACTION" \
     "" "$CONVERT" \
     "" "$EXTRACT" \
     "" "$CHOOSEDEFAULTDIRECTORY"\
     "" "$LANGG"\
     "" "$EXIT" )

case $ASKFIRST in
    "$CONVERT" )
          FILEISO=$(zenity --file-selection --filename="$DEFAULTDIR/" --title="$CHOOSE_IMAGE" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png )
          case $FILEISO in
            0) ;;
           "") break;;
          esac

          DIRNEWISO=$(zenity --file-selection  --filename="$FILEISO" --directory --title="$CHOOSE_DIRECTORY" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png )
                case $DIRNEWISO in
                   0) ;;
                  "") exit;;
                esac
                
          ISOFORMAT=$(zenity --list --radiolist --height=310 --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png \
                --column="" --column="$CHOOSE_FORMAT" \
                   "" "iso" \
                   "" "bin" \
                   "" "mdf" \
                   "" "nrg" \
                   "" "daa"\
                   "" "img")
                   case $ISOFORMAT in
                     iso) DISKFORMAT="iso";;
                     bin) DISKFORMAT="bin";;
                     mdf) DISKFORMAT="mdf";;
                     nrg) DISKFORMAT="nrg";;
                     img) DISKFORMAT="img";;
                     daa) DISKFORMAT="daa";;
                      "") exit;;
                       *) exit;;
                   esac
                   FILENAME=$(basename "$FILEISO" |awk -F"." '{print $1}')
                     zenity --question --title="$YESNO" --text="$IMAGE\n $FILEISO\n $CONVERTED_IN\n $DIRNEWISO/$FILENAME.$DISKFORMAT" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png
                     if [ $? -eq "0" ]; then
                     ##В идеале сделать проверку на файлы в директории
                      find "$DIRNEWISO" -name "$FILENAME.cue" -exec rm -rf {} \;
                      find "$DIRNEWISO" -name "$FILENAME.bin" -exec rm -rf {} \;
                    /usr/sbin/poweriso convert "$FILEISO" -o "$DIRNEWISO"/"$FILENAME"."$DISKFORMAT" -ot "$DISKFORMAT"| tee >(zenity --progress --text="$PROGRESSBAR" --pulsate --auto-close --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png)
                    zenity --info --title "$NORTIFICATION" --text="$COMPLETED" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png 
                    fi
      
    ;;

    "$EXTRACT" )
       FILEISO=$(zenity --file-selection --filename="$DEFAULTDIR/" --title="$CHOOSE_IMAGE" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png )

       case $FILEISO in
         0) ;;
         "") exit;;
        esac

        DIREXTISO=$(zenity --file-selection  --filename="$FILEISO" --directory --title="$CHOOSE_DIRECTORY" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png )
                case $DIREXTISO in
                0) ;;
                "") exit;;
                esac
                FILENAME=$(basename "$FILEISO" |awk -F"." '{print $1}')
                mkdir "$DIREXTISO"/"$FILENAME"
                poweriso extract "$FILEISO" / -od "$DIREXTISO"/"$FILENAME"| tee >(zenity --progress --text="$PROGRESSBAR" --pulsate --auto-close --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png )
                zenity --info --title "$NORTIFICATION" --text "$COMPLETED" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png 
    ;;
    "$CHOOSEDEFAULTDIRECTORY" )
     DEFAULTDIR=$(zenity --file-selection --directory --title="$CHOOSE_IMAGE_DIRECTORY" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png )
     sed -i 's/^DEFAU.*//g' ~/.config/poweriso.conf
     echo "DEFAULTDIR=$DEFAULTDIR" >> ~/.config/poweriso.conf
    ;;
    "$EXIT" )
    exit 0
    ;;
    "Change language (Need restart)" )
    sed -i 's/EN/RU/g' ~/.config/poweriso.conf
    exit 0
    ;;
    "Сменить язык (Нужен перезапуск)" )
    sed -i 's/RU/EN/g' ~/.config/poweriso.conf
    exit 0
    ;;
    "" )
    exit 0
    ;;
    
    * ) zenity --error --text="$ERROR" --window-icon=/usr/share/icons/hicolor/16x16/apps/PowerISO.png 
    ;;

esac
done
